version: "3.8"
services:
        web:
                build: ./node/.
                ports:
                        - 8080:8080
                depends_on:
                        - mong
                volumes:
                       - ./application:/usr/src/app/application
                command: npm run-script dev
        mong:
                build: ./mongodb/.
                hostname: mong
                container_name: mong
                restart: unless-stopped
                ports:
                        - '27017:27017'
                volumes:
                        - 'mongologs:/var/log/mongodb'
                        - 'mongodata:/data/db'
                command:
                        - "--auth"
                        - "--logpath"
                        - "/var/log/mongodb/mongod.log"
volumes:
        mongodata:
        mongologs:
