version: "3.3"
services:
        frontend:
                build: ./frontend/.
                ports:
                        - '3001:3000'
                environment:
                        - CHOKIDAR_USEPOLLING=true
                command: npm start
                depends_on:
                        - mong
                        - backend
        backend:
                build: ./backend/.
                environment:
                        API_HOST: ${API_HOST}
                        APP_SERVER_PORT: ${APP_SERVER_PORT}
                ports:
                        - '8080:8080'
                depends_on:
                        - mong
                command: npm run-script dev
        mong:
                build: ./mongodb/.
                hostname: mong
                container_name: mong
                restart: unless-stopped
                ports:
                        - '27017:27017'
                environment:
                        - MONGO_INITDB_ROOT_USERNAME=admin
                        - MONGO_INITDB_ROOT_PASSWORD=pass
                entrypoint: /usr/local/bin/docker-entrypoint.sh
                command: "--auth"
