version: "3.3"
services:
  frontend:
    build:
      context: ./frontend/.
      dockerfile: Dockerfile.prod
  backend:
    command: npm run-script start
  mong:
    volumes:
      - 'mongologs:/var/log/mongodb'
      - 'mongodata:/data/db'
    command:
      - "--auth"
      - "--logpath"
      - "/var/log/mongodb/mongod.log"
volumes:
  mongodata:
  mongologs:
