version: "3.3"
services:
  frontend:
    volumes:
      - ./frontend:/app
  backend:
    volumes:
      - ./backend:/usr/src/app
  mong:
    volumes:
      - ./mongodb/scripts:/scripts
      - ./mongodb/load_pictures:/load_pictures
      - ./mongodb/load_words:/load_words
